#!/usr/bin/env bash

# 用户自定义变量
BASE_NAME="${0##*/}"
IS_HELP="false"
IS_DEBUG="false"
CLOUD_TYPE="aws"
PROJECT_NAME=""
IS_REFRESH="false"

# 自定义函数
# 用法
function usage()
{
    echo "Usage: ${BASE_NAME} [--debug] [-h|--help] [-r|--refresh] [-t|--type aws|gcp|azure]"    
    exit 1
}
# 初始化
function init()
{
    #gnu-getopt required for macOSX: brew install gnu-getopt && brew link --force gnu-getopt
    ARGS="`getopt -u -o "t:hr" -l "type:,help,debug,refresh" -- "$@"`"
    [ $? -ne 0 ] && usage
    set -- ${ARGS}

    while [ true ] ; do
        case $1 in
            --debug)
                IS_DEBUG="true"
                ;;
            -h|--help)
                IS_HELP="true"
                ;;
            -r|--refresh)
                IS_REFRESH="true"
                ;;
            -t|--type)
                CLOUD_TYPE=$2
                shift
                ;;
            --)
                shift
                break
                ;;
            *)
                usage
                ;;
        esac
        shift
    done

    [ "${IS_HELP}" == "true" ] && usage
    [ "${IS_DEBUG}" == "true" ] && set -x

    PROJECT_NAME=$1

    return
}

function fn_get_aws()
{
    UTIL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../../util && pwd )"
    WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../../../prepare-resource && pwd )"
    LOG_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../../log && pwd )"
    
    source $UTIL_DIR/log.sh

    cd $WORK_DIR
    echo "Start to get project '$1' in cloud '$CLOUD_TYPE'"
    LOG_FILE="project_get.$(date "+%Y%m%d_%H%M%S").log"

    #refresh
    if [ "$IS_REFRESH" == "true" ];then    
        START_TS=$(date +"%s")
        terraform refresh -var PROJECT_NAME=$1 > $LOG_DIR/$LOG_FILE 2>&1 
        fn_log "${LOG_FILE}" "terraform refresh -var PROJECT_NAME=$1"
        END_TS=$(date +"%s")
        echo "refresh duration: $((END_TS-START_TS)) (seconds)"
    else
        echo "<skip refresh dure to without --refresh>"
    fi

    #output
    echo "=============================="
    terraform output
    echo "=============================="
}

# 处理过程
function do_process()
{
    ## check project name
    if [ "$PROJECT_NAME" == "" ];then
        echo "ERROR: project name can not be empty"
        usage
    fi

    ## check cloud type
    case "$CLOUD_TYPE" in
        aws)
            fn_get_aws $PROJECT_NAME
            ;;
        *)
            echo "ERROR: --type only support 'aws' now"
            exit 1
            ;;
    esac
}

############################
# main
############################
init "$@"
do_process
 
exit 0